CREATE TABLE IF NOT EXISTS `ai_persona_memories` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `persona_id` VARCHAR(64) NOT NULL,
  `game_id` VARCHAR(64) NOT NULL,
  `role_key` VARCHAR(64) NOT NULL,
  `memory_summary` LONGTEXT NULL,
  `strategy_notes` LONGTEXT NULL,
  `mistake_notes` LONGTEXT NULL,
  `speech_patterns` LONGTEXT NULL,
  `games_played` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_persona_memory_scope` (`persona_id`, `game_id`, `role_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_decision_traces` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `room_id` VARCHAR(64) NULL,
  `game_id` VARCHAR(64) NOT NULL,
  `phase` VARCHAR(64) NULL,
  `round_number` INT NOT NULL DEFAULT 1,
  `action` VARCHAR(64) NOT NULL,
  `actor_player_id` VARCHAR(64) NULL,
  `persona_id` VARCHAR(64) NULL,
  `role_key` VARCHAR(64) NULL,
  `model_key` VARCHAR(128) NULL,
  `prompt_tokens` BIGINT NOT NULL DEFAULT 0,
  `completion_tokens` BIGINT NOT NULL DEFAULT 0,
  `latency_ms` BIGINT NOT NULL DEFAULT 0,
  `fallback` TINYINT(1) NOT NULL DEFAULT 0,
  `valid_decision` TINYINT(1) NOT NULL DEFAULT 1,
  `confidence` DOUBLE NULL,
  `target_player_id` VARCHAR(64) NULL,
  `night_action` VARCHAR(64) NULL,
  `reason` VARCHAR(512) NULL,
  `output_summary` VARCHAR(512) NULL,
  `input_summary` VARCHAR(1024) NULL,
  `belief_snapshot` LONGTEXT NULL,
  `memory_snapshot` LONGTEXT NULL,
  `quality` LONGTEXT NULL,
  `raw_output` LONGTEXT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_trace_room_id` (`room_id`, `id`),
  KEY `idx_ai_trace_game_action` (`game_id`, `action`, `id`),
  KEY `idx_ai_trace_persona` (`persona_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
